@startuml UC14_CriarClubeDoLivro

skinparam backgroundColor #FFFFFF
skinparam sequenceArrowColor #A389D4
skinparam sequenceArrowFontColor #000000
skinparam sequenceArrowFontSize 11
skinparam participant {
  BackgroundColor #F0EBFF
  BorderColor #C4ADEE
  FontColor #3D2478
  FontSize 12
  FontStyle bold
}
skinparam database {
  BackgroundColor #F0EBFF
  BorderColor #C4ADEE
  FontColor #3D2478
  FontSize 12
  FontStyle bold
}
skinparam actor {
  BackgroundColor #E8DFFF
  BorderColor #A389D4
  FontColor #3D2478
  FontSize 13
  FontStyle bold
}
skinparam sequence {
  LifeLineBorderColor #C4ADEE
  LifeLineBackgroundColor #FFFFFF
  GroupBackgroundColor #FFFFFF
  GroupBorderColor #A389D4
  GroupFontColor #000000
  GroupHeaderFontColor #A389D4
  DividerBackgroundColor #FFFFFF
  DividerBorderColor #000000
  DividerFontColor #000000
  BoxBackgroundColor #FFFFFF
  BoxBorderColor #A389D4
  ActivationBorderColor #7F77DD
  ActivationBackgroundColor #E8DFFF
}
skinparam shadowing false
skinparam roundcorner 12
skinparam noteBorderColor #C4ADEE
skinparam noteBackgroundColor #F0EBFF
skinparam noteFontColor #3D2478

title UC14 — Criar Clube do Livro

actor Leitor
participant "App\n(Mobile)" as App
participant "ClubeController" as CC
participant "ClubeService" as CS
participant "LivroRepository" as LR
participant "ClubeRepository" as CR
participant "MembroRepository" as MR
participant "NotificacaoService" as NS
database "PostgreSQL" as DB

== Criar Clube do Livro ==

Leitor -> App : Acessa "Criar Clube"
activate App

App -> CC : POST /clubes\n{CriarClubeDTO}
activate CC

CC -> CS : criarClube(dto: CriarClubeDTO)
activate CS

CS -> LR : findById(dto.livroId)
activate LR
LR -> DB : SELECT livro WHERE id = livroId
activate DB
DB --> LR : Retorna Livro
deactivate DB
LR --> CS : Livro
deactivate LR

CS -> CR : save(clube: Clube)
activate CR
CR -> DB : INSERT INTO clubes
activate DB
DB --> CR : Clube persistido
deactivate DB
CR --> CS : Clube
deactivate CR

CS -> MR : save(membro: MembroClube\n{papel: ADMIN})
activate MR
MR -> DB : INSERT INTO membros_clube
activate DB
DB --> MR : MembroClube persistido
deactivate DB
MR --> CS : MembroClube
deactivate MR

alt [privacidade == PRIVADO]
  note over CS : Gera codigoAcesso\ne associa ao Clube
end

CS -> NS : enviarNotificacao(usuarioId,\nCLUBE_CRIADO, payload)
activate NS
NS --> CS : ok
deactivate NS

CS --> CC : Clube criado
deactivate CS

CC --> App : 201 Created {clube}
deactivate CC

App --> Leitor : Exibe painel do clube
deactivate App

@enduml
